# Generated by Django 2.0.8 on 2018-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
