# Generated by Django 2.0.8 on 2018-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181130_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='media/avatars/anonymous.png', null=True, upload_to='avatars'),
        ),
    ]
