# Generated by Django 2.0.8 on 2018-12-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181210_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='avatars/anonymous.png', null=True, upload_to='avatars'),
        ),
    ]
