# Generated by Django 2.0.8 on 2018-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181210_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='/avatars/anonymous.png', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='lover',
            name='image',
            field=models.ImageField(blank=True, default='/avatars/anonymous.png', null=True, upload_to='avatars'),
        ),
    ]
